namespace vertical_tasks
{
    [default_interface]
    runtimeclass TaskVM : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        TaskVM(UInt64 hwnd);
        String Title{ get; };
        Microsoft.UI.Xaml.Media.Imaging.SoftwareBitmapSource IconSource{ get; set; };

        void Select();
        void Close();

    }

    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();
        Windows.Foundation.Collections.IObservableVector<Object> Tasks{ get; };
    }
}
